experiment_name: sd_savgol_tcn_w78
model_name: enhanced_tcn_last
use_pressure: true
use_diff: true
use_ddiff: true
input_dim: 14
output_dim: 4
num_channels: [78, 78, 78]
kernel_size: 7
dropout: 0.4
diff_method: savgol
savgol_window: 11
savgol_polyorder: 3
dt: 0.005
label_shift: 0
return_contact_mask: false
model_uses_contact_mask: false
loss_type: mse
sampler_type: default
window: 180
stride: 30
batch_size: 64
lr: 0.0001
optimizer: Adam
max_epochs: 100
patience: 10
scaler_method: zscore
clip_data: true
